#!/bin/bash
# HuggingFace 模型更新监控 - 正确方式

echo "📦 推荐关注的 HuggingFace 组织/用户"
echo "========================================"
echo ""
echo "🔹 Google (Gemma 模型)"
echo "   https://huggingface.co/google"
echo "   点击 Follow 按钮以获取 Gemma 系列更新"
echo ""
echo "🔹 Qwen (通义千问)"
echo "   https://huggingface.co/Qwen"
echo "   点击 Follow 按钮以获取 Qwen 系列更新"
echo ""
echo "🔹 MLX Community"
echo "   https://huggingface.co/mlx-community"
echo "   点击 Follow 按钮以获取 MLX 转换模型更新"
echo ""
echo "🔹 Jiunsong (SuperGemma 作者)"
echo "   https://huggingface.co/Jiunsong"
echo "   点击 Follow 按钮以获取 SuperGemma 更新"
echo ""
echo "🔹 NVIDIA"
echo "   https://huggingface.co/nvidia"
echo "   点击 Follow 按钮以获取 NVIDIA 模型更新"
echo ""
echo "========================================"
echo "💡 提示: Follow 后，当这些组织发布新模型或更新时，"
echo "   你会在 HuggingFace 首页看到动态更新"
echo "========================================"
