#!/bin/bash
# HuggingFace 搜索 - Unsloth MLX 模型

echo "🔍 HuggingFace 搜索链接 - Unsloth MLX 模型"
echo "================================================"
echo ""

echo "方法 1: 直接搜索链接"
echo "-------------------"
echo "Qwen 系列:"
echo "https://huggingface.co/models?search=unsloth+qwen+mlx"
echo ""
echo "Gemma 系列:"
echo "https://huggingface.co/models?search=unsloth+gemma+mlx"
echo ""
echo "所有 Unsloth MLX:"
echo "https://huggingface.co/models?search=unsloth+mlx"
echo ""

echo "================================================"
echo "方法 2: 访问 Unsloth 主页"
echo "================================================"
echo "https://huggingface.co/unsloth"
echo ""
echo "然后点击 'Models' 标签，在搜索框输入: mlx"
echo ""

echo "================================================"
echo "方法 3: 使用 Python 脚本搜索"
echo "================================================"
echo "运行: python3 /Users/berton/Github/omlx/search_hf_models.py"
echo ""

echo "================================================"
echo "常用 Unsloth MLX 模型"
echo "================================================"
echo ""
echo "📌 Qwen 系列:"
echo "   unsloth/Qwen3.6-27B-UD-MLX-4bit"
echo "   unsloth/Qwen3.6-35B-A3B-MLX-4bit"
echo ""
echo "📌 Gemma 系列:"
echo "   unsloth/gemma-4-31b-it-UD-MLX-4bit"
echo "   unsloth/gemma-4-26B-A4B-it-MLX-4bit"
echo ""
echo "📌 其他:"
echo "   unsloth/Llama-3.1-8B-Instruct-MLX-4bit"
echo ""
